Update Jekyll config to exclude 'vendor' sub-dir
To be able to run `bundle install` on local env without sudo,
bundle installs everything under ./vendor/bundle by default.

If not excluded, Jekyll will try to build default posts from it
and fail with

```
 Generating...
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.0.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename.
```