Update async cpp example be compatible \w latest Liquid
On local env Jekyll 2.4.0 is installed though Bundler and by default fails with

```
Error: Variable '{{' was not properly terminated with regexp: /\}\}/
```

Reason is a known issue in the new Liquid template parser, used since Jekyll 2.0
https://jekyllrb.com/docs/troubleshooting/#liquid wich requires closing
`{{` on the same line `}}`.

This results in ugly long lines, but at least makes Jekyll 2.4.0 build
the site locally